// <auto-generated />
using System;
using FamilyFitness.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FamilyFitness.Infrastructure.Migrations
{
    [DbContext(typeof(FamilyFitnessDbContext))]
    [Migration("20260105183325_InitialWorkoutDataModel")]
    partial class InitialWorkoutDataModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FamilyFitness.Domain.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("FamilyFitness.Domain.GroupMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GroupId", "UserId")
                        .IsUnique();

                    b.ToTable("group_memberships", (string)null);
                });

            modelBuilder.Entity("FamilyFitness.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("FamilyFitness.Domain.WorkoutIntervalScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("StationIndex")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("WorkoutTypeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId", "RoundNumber", "StationIndex")
                        .IsUnique();

                    b.HasIndex("ParticipantId", "WorkoutTypeId", "RecordedAt");

                    b.ToTable("workout_interval_scores", null, t =>
                        {
                            t.HasCheckConstraint("CK_WorkoutIntervalScore_RoundNumber", "\"RoundNumber\" >= 1 AND \"RoundNumber\" <= 3");

                            t.HasCheckConstraint("CK_WorkoutIntervalScore_Score", "\"Score\" >= 0");

                            t.HasCheckConstraint("CK_WorkoutIntervalScore_StationIndex", "\"StationIndex\" >= 1 AND \"StationIndex\" <= 4");
                        });
                });

            modelBuilder.Entity("FamilyFitness.Domain.WorkoutSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("GroupId", "SessionDate");

                    b.ToTable("workout_sessions", (string)null);
                });

            modelBuilder.Entity("FamilyFitness.Domain.WorkoutSessionParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ParticipantIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkoutSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkoutSessionId", "ParticipantIndex")
                        .IsUnique();

                    b.HasIndex("WorkoutSessionId", "UserId")
                        .IsUnique();

                    b.ToTable("workout_session_participants", (string)null);
                });

            modelBuilder.Entity("FamilyFitness.Domain.WorkoutSessionWorkoutType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("StationIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkoutSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorkoutTypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutSessionId", "StationIndex")
                        .IsUnique();

                    b.ToTable("workout_session_workout_types", null, t =>
                        {
                            t.HasCheckConstraint("CK_WorkoutSessionWorkoutType_StationIndex", "\"StationIndex\" >= 1 AND \"StationIndex\" <= 4");
                        });
                });

            modelBuilder.Entity("FamilyFitness.Infrastructure.WorkoutTypeEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("workout_types", (string)null);
                });

            modelBuilder.Entity("FamilyFitness.Domain.GroupMembership", b =>
                {
                    b.HasOne("FamilyFitness.Domain.Group", "Group")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyFitness.Domain.User", "User")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FamilyFitness.Domain.WorkoutIntervalScore", b =>
                {
                    b.HasOne("FamilyFitness.Domain.WorkoutSessionParticipant", "Participant")
                        .WithMany("IntervalScores")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("FamilyFitness.Domain.WorkoutSession", b =>
                {
                    b.HasOne("FamilyFitness.Domain.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyFitness.Domain.Group", "Group")
                        .WithMany("WorkoutSessions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("FamilyFitness.Domain.WorkoutSessionParticipant", b =>
                {
                    b.HasOne("FamilyFitness.Domain.User", "User")
                        .WithMany("WorkoutSessionParticipants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyFitness.Domain.WorkoutSession", "WorkoutSession")
                        .WithMany("Participants")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("FamilyFitness.Domain.WorkoutSessionWorkoutType", b =>
                {
                    b.HasOne("FamilyFitness.Domain.WorkoutSession", "WorkoutSession")
                        .WithMany("WorkoutSessionWorkoutTypes")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("FamilyFitness.Domain.Group", b =>
                {
                    b.Navigation("GroupMemberships");

                    b.Navigation("WorkoutSessions");
                });

            modelBuilder.Entity("FamilyFitness.Domain.User", b =>
                {
                    b.Navigation("GroupMemberships");

                    b.Navigation("WorkoutSessionParticipants");
                });

            modelBuilder.Entity("FamilyFitness.Domain.WorkoutSession", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("WorkoutSessionWorkoutTypes");
                });

            modelBuilder.Entity("FamilyFitness.Domain.WorkoutSessionParticipant", b =>
                {
                    b.Navigation("IntervalScores");
                });
#pragma warning restore 612, 618
        }
    }
}
